version: '3'
services:
  elasticsearch:
    image: errorecho/cve-2021-22146
    container_name: CVE-2021-22146
    restart: always
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
